task:
  name: Build Sapphiren Rom
  timeout_in: 4h # Лимит бесплатной сессии
  container:
    image: aospbuild/ubuntu-22.04:latest # Специальный образ для сборки Android
    cpu: 8
    memory: 24G
    volumes:
      - /tmp/android:/tmp/android # Используем временный диск Cirrus

  build_script:
    - export git_user="mbov777"
    - export git_email="imya777821@gmail.com"
    - git config --global user.name "$git_user"
    - git config --global user.email "$git_email"
    - mkdir -p /tmp/android && cd /tmp/android
    # Инициализация с максимальной экономией места
    - repo init -u https://github.com/crdroidandroid/android.git -b 13.0 --depth=1
    - repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
    # Клонируем дерево устройства
    - git clone https://github.com/crdroidandroid/android_device_xiaomi_sapphire -b 13.0 device/xiaomi/sapphire --depth=1
    - git clone https://github.com/TheMuppets/proprietary_vendor_xiaomi_sapphire -b 13.0 vendor/xiaomi/sapphire --depth=1
    - git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6225 -b lineage-20 kernel/xiaomi/chime --depth=1
    # Сборка
    - source build/envsetup.sh
    - lunch lineag_sapphire-userdebug
    - mka bacon -j8
