container:
  image: aospbuild/aosp:latest # Специальный образ со всеми утилитами
  cpu: 8
  memory: 32G

task:
  name: MegamboOS_Build_A14
  timeout_in: 4h # Cirrus дает больше времени на сборку

  environment:
    USER_NAME: "mbov777"
    USER_EMAIL: "megambo@example.com"

  cleanup_script:
    - rm -rf /tmp/* # Очистка временных файлов перед стартом

  sync_script:
    - git config --global user.name "$USER_NAME"
    - git config --global user.email "$USER_EMAIL"
    - mkdir -p ~/android && cd ~/android
    - repo init -u https://github.com/crdroidandroid/android.git -b 14.0 --depth=1
    - repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
    
  clone_trees_script:
    - cd ~/android
    - git clone https://github.com/crdroidandroid/android_device_xiaomi_sapphire -b 14.0 device/xiaomi/sapphire --depth=1
    - git clone https://github.com/TheMuppets/proprietary_vendor_xiaomi_sapphire -b 14.0 vendor/xiaomi/sapphire --depth=1
    - git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6225 -b lineage-21 kernel/xiaomi/chime --depth=1
    - git clone https://github.com/LineageOS/android_hardware_xiaomi -b lineage-21 hardware/xiaomi --depth=1

  build_script:
    - cd ~/android
    - source build/envsetup.sh
    - lunch lineage_sapphire-userdebug
    - mka bacon -j8

  upload_artifacts:
    path: "~/android/out/target/product/sapphire/*.zip"
