name: Build MegamboOS (Final Fix)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space (Тотальная очистка)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost /usr/lib/jvm /usr/local/share/powershell /usr/share/swift
          docker image prune -a -f
          sudo apt-get clean
          echo "Свободное место перед началом:"
          df -h | grep "/$"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo
          git config --global user.name "mbov777"
          git config --global user.email "megambo@example.com"

      - name: Sync Source (Загрузка системы)
        run: |
          mkdir -p ~/android && cd ~/android
          repo init -u https://github.com/crdroidandroid/android.git -b 13.0 --depth=1 --git-lfs
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          echo "Место после загрузки исходников:"
          df -h | grep "/$"

      - name: Clone Device Tree (Драйверы Redmi Note 13 4G)
        run: |
          cd ~/android
          git clone https://github.com/crdroidandroid/android_device_xiaomi_sapphire -b 13 device/xiaomi/sapphire --depth=1
          git clone https://github.com/TheMuppets/proprietary_vendor_xiaomi_sapphire -b 13 vendor/xiaomi/sapphire --depth=1
          git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6225 -b lineage-20 kernel/xiaomi/chime --depth=1
          git clone https://github.com/LineageOS/android_hardware_xiaomi -b lineage-20 hardware/xiaomi --depth=1

      - name: Build Firmware (Компиляция)
        run: |
          cd ~/android
          source build/envsetup.sh
          lunch lineag_sapphire-userdebug
          mka bacon -j$(nproc --all)

      - name: Upload Artifact (Выгрузка файла)
        uses: actions/upload-artifact@v4
        with:
          name: MegamboOS-RedmiNote13
          path: ~/android/out/target/product/sapphire/*.zip
